 var jobData = [
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Professor E",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Academic",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Fellow",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Academic",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Technical Officer- III",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Technical",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Technical Officer - I",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Technical",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Senior Technical Assistant",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Technical",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Technical Assistant",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Technical",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Stenographer Grade -II",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Administrative",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Peon/Multi Tasking Staff",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Administrative",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "05/IIG/HRD/2023",
    "title": "Driver",
    "organization": "Indian Institute of Geomagnetism",
    "qualification": "As Per ToR",
    "location": "Mumbai, Maharashtra",
    "category": "Administrative",
    "castcategory": null,
    "doc": "https://iigm.res.in/system/files/ADVT%202023-detailed-2%20_1_24-Revised.pdf",
    "link": "https://iigm.formsubmit.in/ep_ses_web_landing",
    "employmenttype": "Direct",
    "age": null,
    "Closingdate": "2024-02-19"
  },
  {
    "advno": "39/2023 dt. 22/12/2023",
    "title": "Accounts & Finance Officer",
    "organization": "National Institute of Rural Development & Panchayati Raj, Hyderabad",
    "qualification": "As Per ToR",
    "location": "Hyderabad, Telangana",
    "category": "Finance",
    "castcategory": "Not Applicable",
    "doc": "http://career.nirdpr.in/Uploads/Radvertisment/RAdv_39_2023.pdf",
    "link": "http://career.nirdpr.in/",
    "employmenttype": "Deputation",
    "age": 56.0,
    "Closingdate": "2024-03-06"
  },
  {
    "advno": "1/2024 dt. 12/01/2024",
    "title": "IT Support Engineer",
    "organization": "National Institute of Rural Development & Panchayati Raj, Hyderabad",
    "qualification": "As Per ToR",
    "location": "Hyderabad, Telangana",
    "category": "Technical",
    "castcategory": "Not Applicable",
    "doc": "http://career.nirdpr.in/Uploads/Radvertisment/RAdv_1_2024.pdf",
    "link": "http://career.nirdpr.in/",
    "employmenttype": "Contract",
    "age": 30.0,
    "Closingdate": "2024-01-28"
  }
];